name: grammar-based-agent-autotrain
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
dependencies:
  - python=3.9
  - pytorch=2.1
  - pytorch-cuda=11.8
  - cuda-toolkit
  - pip
  - pip:
    - autotrain-advanced
