name: krasserm-gba-autotrain
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.2
  - pytorch-cuda=12.1
  - cuda-toolkit
  - pip
  - pip:
    - autotrain-advanced==0.7.101
    - deepspeed==0.14.2
